server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  thymeleaf:
    cache: false
  datasource:
    url:  jdbc:mysql://localhost:3306/hotel_project?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: test1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    open-in-view: false

mail:
  default-encoding: UTF-8
  host: smtp.gmail.com
  port: 587
  username: projecthotel.roxfort@gmail.com
  password: ilzn nqfp fwjz gviy
  protocol: smtp
  properties.mail.smtp:
    auth: true
    starttls.enable: true
    ssl.trust: smtp.gmail.com

logging:
  level:
    org.hotel: info
    org.springframework.web: info
    org.hibernate: error
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"



cloudinary.cloud_name: de8m1v9be
cloudinary.api_key: 958846475439791
cloudinary.api_secret: bCCw6w3w6u3SraNmkt9de0I4Og0

paypal.mode: sandbox
paypal.client.id: AUBBH7ml_7cvytC1Qe5tuvAWAYWaFStSp8TGCRWaMXTzE8qsZn8YyHDF86ZJBL91iN_z1YGCrf11nk16
paypal.client.secret: EC0lzA5U2FJlPENBE7DYQU0LUuHAz1STfbwnyzswj4zRerO2GIIdjPjATYXkxxhvY9CpFiO7D4JVXpzI

openexchangerates:
  api:
    key: 7380726a8dd0436c93547515696916 28
    url: https://openexchangerates.org/api/

openweathermap:
  api:
    key: dead026e9d7edf0b9d08814949446cbc

#security.jwt.secret: hotelProject
#security.jwt.expiration: 31536000000
#security.jwt.refresh: 2592000000